/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by LCM
 **/

#include <string.h>
#include "mrlcm_obj_collection_t.h"

static int __mrlcm_obj_collection_t_hash_computed;
static int64_t __mrlcm_obj_collection_t_hash;
 
int64_t __mrlcm_obj_collection_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __mrlcm_obj_collection_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__mrlcm_obj_collection_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x207e172f8d8dba1dLL
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __mrlcm_obj_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __mrlcm_obj_collection_t_get_hash(void)
{
    if (!__mrlcm_obj_collection_t_hash_computed) {
        __mrlcm_obj_collection_t_hash = __mrlcm_obj_collection_t_hash_recursive(NULL);
        __mrlcm_obj_collection_t_hash_computed = 1;
    }
 
    return __mrlcm_obj_collection_t_hash;
}
 
int __mrlcm_obj_collection_t_encode_array(void *buf, int offset, int maxlen, const mrlcm_obj_collection_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].name), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].type), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].reset), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nobjs), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __mrlcm_obj_t_encode_array(buf, offset + pos, maxlen - pos, p[element].objs, p[element].nobjs);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int mrlcm_obj_collection_t_encode(void *buf, int offset, int maxlen, const mrlcm_obj_collection_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __mrlcm_obj_collection_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __mrlcm_obj_collection_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __mrlcm_obj_collection_t_encoded_array_size(const mrlcm_obj_collection_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int32_t_encoded_array_size(&(p[element].id), 1);
 
        size += __string_encoded_array_size(&(p[element].name), 1);
 
        size += __int16_t_encoded_array_size(&(p[element].type), 1);
 
        size += __boolean_encoded_array_size(&(p[element].reset), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].nobjs), 1);
 
        size += __mrlcm_obj_t_encoded_array_size(p[element].objs, p[element].nobjs);
 
    }
    return size;
}
 
int mrlcm_obj_collection_t_encoded_size(const mrlcm_obj_collection_t *p)
{
    return 8 + __mrlcm_obj_collection_t_encoded_array_size(p, 1);
}
 
int __mrlcm_obj_collection_t_decode_array(const void *buf, int offset, int maxlen, mrlcm_obj_collection_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].name), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].type), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].reset), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nobjs), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].objs = (mrlcm_obj_t*) lcm_malloc(sizeof(mrlcm_obj_t) * p[element].nobjs);
        thislen = __mrlcm_obj_t_decode_array(buf, offset + pos, maxlen - pos, p[element].objs, p[element].nobjs);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __mrlcm_obj_collection_t_decode_array_cleanup(mrlcm_obj_collection_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int32_t_decode_array_cleanup(&(p[element].id), 1);
 
        __string_decode_array_cleanup(&(p[element].name), 1);
 
        __int16_t_decode_array_cleanup(&(p[element].type), 1);
 
        __boolean_decode_array_cleanup(&(p[element].reset), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].nobjs), 1);
 
        __mrlcm_obj_t_decode_array_cleanup(p[element].objs, p[element].nobjs);
        if (p[element].objs) free(p[element].objs);
 
    }
    return 0;
}
 
int mrlcm_obj_collection_t_decode(const void *buf, int offset, int maxlen, mrlcm_obj_collection_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __mrlcm_obj_collection_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __mrlcm_obj_collection_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int mrlcm_obj_collection_t_decode_cleanup(mrlcm_obj_collection_t *p)
{
    return __mrlcm_obj_collection_t_decode_array_cleanup(p, 1);
}
 
int __mrlcm_obj_collection_t_clone_array(const mrlcm_obj_collection_t *p, mrlcm_obj_collection_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int32_t_clone_array(&(p[element].id), &(q[element].id), 1);
 
        __string_clone_array(&(p[element].name), &(q[element].name), 1);
 
        __int16_t_clone_array(&(p[element].type), &(q[element].type), 1);
 
        __boolean_clone_array(&(p[element].reset), &(q[element].reset), 1);
 
        __int32_t_clone_array(&(p[element].nobjs), &(q[element].nobjs), 1);
 
        q[element].objs = (mrlcm_obj_t*) lcm_malloc(sizeof(mrlcm_obj_t) * q[element].nobjs);
        __mrlcm_obj_t_clone_array(p[element].objs, q[element].objs, p[element].nobjs);
 
    }
    return 0;
}
 
mrlcm_obj_collection_t *mrlcm_obj_collection_t_copy(const mrlcm_obj_collection_t *p)
{
    mrlcm_obj_collection_t *q = (mrlcm_obj_collection_t*) malloc(sizeof(mrlcm_obj_collection_t));
    __mrlcm_obj_collection_t_clone_array(p, q, 1);
    return q;
}
 
void mrlcm_obj_collection_t_destroy(mrlcm_obj_collection_t *p)
{
    __mrlcm_obj_collection_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int mrlcm_obj_collection_t_publish(lcm_t *lc, const char *channel, const mrlcm_obj_collection_t *p)
{
      int max_data_size = mrlcm_obj_collection_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = mrlcm_obj_collection_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _mrlcm_obj_collection_t_subscription_t {
    mrlcm_obj_collection_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void mrlcm_obj_collection_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    mrlcm_obj_collection_t p;
    memset(&p, 0, sizeof(mrlcm_obj_collection_t));
    status = mrlcm_obj_collection_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding mrlcm_obj_collection_t!!!\n", status);
        return;
    }

    mrlcm_obj_collection_t_subscription_t *h = (mrlcm_obj_collection_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    mrlcm_obj_collection_t_decode_cleanup (&p);
}

mrlcm_obj_collection_t_subscription_t* mrlcm_obj_collection_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    mrlcm_obj_collection_t_handler_t f, void *userdata)
{
    mrlcm_obj_collection_t_subscription_t *n = (mrlcm_obj_collection_t_subscription_t*)
                       malloc(sizeof(mrlcm_obj_collection_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 mrlcm_obj_collection_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg mrlcm_obj_collection_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int mrlcm_obj_collection_t_unsubscribe(lcm_t *lcm, mrlcm_obj_collection_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe mrlcm_obj_collection_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

